import { expect, test } from "@playwright/test";

test("create, manage, search, and rotate the edit key", async ({ page, browser }) => {
  await page.goto("/create");
  await page.getByLabel("站点名称 *").fill("E2E Team Workspace");
  const captcha = page.locator("#captcha-answer");
  await expect(captcha).toBeVisible();
  const label = await page.locator('label[for="captcha-answer"]').textContent();
  const numbers = label?.match(/(\d+)\s*\+\s*(\d+)/);
  expect(numbers).not.toBeNull();
  await captcha.fill(String(Number(numbers?.[1]) + Number(numbers?.[2])));
  await page.getByRole("button", { name: "创建导航站" }).click();
  await expect(page.getByText("创建完成")).toBeVisible();
  await page.locator('.save-confirm input[type="checkbox"]').check();
  const oldManageUrl = await page.getByTestId("manage-link").getAttribute("href");
  expect(oldManageUrl).toContain("?key=");
  await page.getByTestId("manage-link").click();
  await expect(page.getByText("管理模式")).toBeVisible();

  await page.getByLabel("分类名称").fill("Engineering");
  await page.getByTitle("添加分类").click();
  await expect(page.locator('.category-name-input[value="Engineering"]')).toBeVisible();
  const sourceHandle = page.getByRole("button", { name: "拖拽 Engineering 分类" });
  const handles = page.getByRole("button", { name: /拖拽 .* 分类/ });
  const categoryCount = await handles.count();
  const targetHandle = handles.nth(categoryCount - 2);
  await sourceHandle.scrollIntoViewIfNeeded();
  const sourceBox = await sourceHandle.boundingBox();
  const targetBox = await targetHandle.boundingBox();
  expect(sourceBox).not.toBeNull();
  expect(targetBox).not.toBeNull();
  await page.mouse.move(sourceBox!.x + sourceBox!.width / 2, sourceBox!.y + sourceBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(sourceBox!.x + sourceBox!.width / 2 + 10, sourceBox!.y + sourceBox!.height / 2, { steps: 4 });
  await page.mouse.move(targetBox!.x + targetBox!.width / 2, targetBox!.y + targetBox!.height / 2, { steps: 12 });
  await page.mouse.up();
  await expect(page.locator(".category-name-input").nth(categoryCount - 2)).toHaveValue("Engineering");
  const addLink = page.getByTestId("add-link-form");
  await addLink.locator("select").selectOption({ label: "Engineering" });
  await page.getByLabel("链接名称").fill("Team Portal");
  await page.getByLabel("链接 URL").fill("https://example.com/portal");
  await page.getByLabel("链接标签").fill("team, docs");
  await addLink.getByRole("button", { name: "添加链接" }).click();
  const linkRow = page.locator(".manage-link").filter({ hasText: "Team Portal" });
  await expect(linkRow).toBeVisible();
  await linkRow.getByTitle("编辑").click();
  const modal = page.locator(".modal").filter({ hasText: "编辑链接" });
  await modal.locator("input").nth(0).fill("Engineering Portal");
  await modal.getByRole("button", { name: "保存链接" }).click();
  await expect(page.locator(".manage-link").filter({ hasText: "Engineering Portal" })).toBeVisible();

  const slug = new URL(oldManageUrl!).pathname.split("/").at(-1);
  const publicPage = await page.context().newPage();
  await publicPage.goto(`/s/${slug}`);
  await publicPage.getByLabel("搜索导航链接").fill("engineering");
  await expect(publicPage.getByText("Engineering Portal")).toBeVisible();
  await publicPage.close();

  await page.locator("details.danger-zone summary").click();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "轮换私密编辑链接" }).click();
  const newManageUrl = await page.locator(".rotated-url").textContent();
  expect(newManageUrl).toContain("?key=");
  const freshContext = await browser.newContext();
  const verificationPage = await freshContext.newPage();
  await verificationPage.goto(oldManageUrl!);
  await expect(verificationPage.getByText("无法进入管理模式")).toBeVisible();
  await verificationPage.goto(newManageUrl!);
  await expect(verificationPage.getByText("管理模式")).toBeVisible();
  await freshContext.close();
});
